### write csv

In [41]:
import pandas as pd

In [42]:
dis = {"a":[1,2,3,4,5,6],"b":[4,5,6,7,8,9],"c":[1,5,6,2,4,6]}

d =pd.DataFrame(dis)

print(d)

   a  b  c
0  1  4  1
1  2  5  5
2  3  6  6
3  4  7  2
4  5  8  4
5  6  9  6

In [43]:
d.to_csv("Test_new.csv")

In [44]:
d.to_csv("Test_new1.csv",index=False)

In [45]:
d.to_csv("Test_new2.csv",index=False,header=[1,2,3])

### read csv

In [46]:
csv_1 =pd.read_csv("/home/yksaini/GENAI/GENAI/4-Pandas/data.csv")

csv_1

,seriesuid,coordX,coordY,coordZ,diameter_mm
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-128.699421,-175.319272,-298.387506,5.651471
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,103.783651,-211.925149,-227.121250,4.224708
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,69.639017,-140.944586,876.374496,5.786348
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,-24.013824,192.102405,-391.081276,8.143262
4,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,2.441547,172.464881,-405.493732,18.545150
5,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,90.931713,149.027266,-426.544715,18.208570
6,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,89.540769,196.405159,-515.073322,16.381276
7,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,81.509646,54.957219,-150.346423,10.362321
8,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,105.055792,19.825260,-91.247251,21.089619
9,1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...,-124.834262,127.247155,-473.064479,10.465854
10,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,-106.901301,21.922987,-126.916900,9.745259
11,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,2.263816,33.526418,-170.636950,7.168542

In [47]:
csv_1 =pd.read_csv("/home/yksaini/GENAI/GENAI/4-Pandas/data.csv",nrows =4)

csv_1

,seriesuid,coordX,coordY,coordZ,diameter_mm
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-128.699421,-175.319272,-298.387506,5.651471
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,103.783651,-211.925149,-227.121250,4.224708
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,69.639017,-140.944586,876.374496,5.786348
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,-24.013824,192.102405,-391.081276,8.143262

In [48]:
csv_1 =pd.read_csv("/home/yksaini/GENAI/GENAI/4-Pandas/data.csv",usecols=["coordY","coordX"])

csv_1

        coordX      coordY
0  -128.699421 -175.319272
1   103.783651 -211.925149
2    69.639017 -140.944586
3   -24.013824  192.102405
4     2.441547  172.464881
5    90.931713  149.027266
6    89.540769  196.405159
7    81.509646   54.957219
8   105.055792   19.825260
9  -124.834262  127.247155
10 -106.901301   21.922987
11    2.263816   33.526418

In [49]:
csv_1 =pd.read_csv("/home/yksaini/GENAI/GENAI/4-Pandas/data.csv", skiprows =[0,2])

csv_1

,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860,-128.6994211,-175.3192718,-298.3875064,5.651470635
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,69.639017,-140.944586,876.374496,5.786348
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,-24.013824,192.102405,-391.081276,8.143262
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,2.441547,172.464881,-405.493732,18.545150
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,90.931713,149.027266,-426.544715,18.208570
4,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,89.540769,196.405159,-515.073322,16.381276
5,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,81.509646,54.957219,-150.346423,10.362321
6,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,105.055792,19.825260,-91.247251,21.089619
7,1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...,-124.834262,127.247155,-473.064479,10.465854
8,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,-106.901301,21.922987,-126.916900,9.745259
9,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,2.263816,33.526418,-170.636950,7.168542

In [50]:
csv_1 =pd.read_csv("/home/yksaini/GENAI/GENAI/4-Pandas/data.csv",index_col ="coordX")

csv_1

,seriesuid,coordY,coordZ,diameter_mm
coordX,,,,
-128.699421,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-175.319272,-298.387506,5.651471
103.783651,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-211.925149,-227.121250,4.224708
69.639017,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,-140.944586,876.374496,5.786348
-24.013824,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,192.102405,-391.081276,8.143262
2.441547,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,172.464881,-405.493732,18.545150
90.931713,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,149.027266,-426.544715,18.208570
89.540769,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,196.405159,-515.073322,16.381276
81.509646,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,54.957219,-150.346423,10.362321
105.055792,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,19.825260,-91.247251,21.089619
-124.834262,1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...,127.247155,-473.064479,10.465854
-106.901301,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,21.922987,-126.916900,9.745259
2.263816,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,33.526418,-170.636950,7.168542

In [51]:
csv_1 =pd.read_csv("/home/yksaini/GENAI/GENAI/4-Pandas/data.csv",header = 2)

csv_1

,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860,103.7836509,-211.9251487,-227.12125,4.224708481
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,69.639017,-140.944586,876.374496,5.786348
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,-24.013824,192.102405,-391.081276,8.143262
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,2.441547,172.464881,-405.493732,18.545150
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,90.931713,149.027266,-426.544715,18.208570
4,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,89.540769,196.405159,-515.073322,16.381276
5,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,81.509646,54.957219,-150.346423,10.362321
6,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,105.055792,19.825260,-91.247251,21.089619
7,1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...,-124.834262,127.247155,-473.064479,10.465854
8,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,-106.901301,21.922987,-126.916900,9.745259
9,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,2.263816,33.526418,-170.636950,7.168542

In [52]:
csv_1 =pd.read_csv("/home/yksaini/GENAI/GENAI/4-Pandas/data.csv",names =["col1","col2","coll3"])

csv_1

                                                                         col1  \
seriesuid                                          coordX              coordY
1.3.6.1.4.1.14519.5.2.1.6279.6001.1002252872223... -128.6994211  -175.3192718
                                                   103.7836509   -211.9251487
1.3.6.1.4.1.14519.5.2.1.6279.6001.1003981387935... 69.63901724   -140.9445859
1.3.6.1.4.1.14519.5.2.1.6279.6001.1006213830162... -24.0138242    192.1024053
                                                   2.441546798    172.4648812
                                                   90.93171321    149.0272657
                                                   89.54076865    196.4051593
1.3.6.1.4.1.14519.5.2.1.6279.6001.1009534830281... 81.50964574     54.9572186
1.3.6.1.4.1.14519.5.2.1.6279.6001.1026819624084... 105.0557924    19.82526014
1.3.6.1.4.1.14519.5.2.1.6279.6001.1045627377601... -124.8342624   127.2471546
1.3.6.1.4.1.14519.5.2.1.6279.6001.1054950289858... -106.9013014   21.92298672
1.3.6.1.4.1.14519.5.2.1.6279.6001.1061649783701... 2.263815885    33.52641757

                                                                         col2  \
seriesuid                                          coordX              coordZ
1.3.6.1.4.1.14519.5.2.1.6279.6001.1002252872223... -128.6994211  -298.3875064
                                                   103.7836509     -227.12125
1.3.6.1.4.1.14519.5.2.1.6279.6001.1003981387935... 69.63901724    876.3744957
1.3.6.1.4.1.14519.5.2.1.6279.6001.1006213830162... -24.0138242   -391.0812764
                                                   2.441546798   -405.4937318
                                                   90.93171321   -426.5447146
                                                   89.54076865   -515.0733216
1.3.6.1.4.1.14519.5.2.1.6279.6001.1009534830281... 81.50964574   -150.3464233
1.3.6.1.4.1.14519.5.2.1.6279.6001.1026819624084... 105.0557924   -91.24725078
1.3.6.1.4.1.14519.5.2.1.6279.6001.1045627377601... -124.8342624  -473.0644785
1.3.6.1.4.1.14519.5.2.1.6279.6001.1054950289858... -106.9013014  -126.9169003
1.3.6.1.4.1.14519.5.2.1.6279.6001.1061649783701... 2.263815885   -170.6369497

                                                                       coll3
seriesuid                                          coordX        diameter_mm
1.3.6.1.4.1.14519.5.2.1.6279.6001.1002252872223... -128.6994211  5.651470635
                                                   103.7836509   4.224708481
1.3.6.1.4.1.14519.5.2.1.6279.6001.1003981387935... 69.63901724   5.786347814
1.3.6.1.4.1.14519.5.2.1.6279.6001.1006213830162... -24.0138242   8.143261683
                                                   2.441546798   18.54514997
                                                   90.93171321   18.20857028
                                                   89.54076865   16.38127631
1.3.6.1.4.1.14519.5.2.1.6279.6001.1009534830281... 81.50964574   10.36232088
1.3.6.1.4.1.14519.5.2.1.6279.6001.1026819624084... 105.0557924   21.08961863
1.3.6.1.4.1.14519.5.2.1.6279.6001.1045627377601... -124.8342624  10.46585391
1.3.6.1.4.1.14519.5.2.1.6279.6001.1054950289858... -106.9013014  9.745258507
1.3.6.1.4.1.14519.5.2.1.6279.6001.1061649783701... 2.263815885    7.16854239

In [53]:
csv_1 =pd.read_csv("/home/yksaini/GENAI/GENAI/4-Pandas/data.csv",dtype={"coordY" :"float"})

csv_1

,seriesuid,coordX,coordY,coordZ,diameter_mm
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-128.699421,-175.319272,-298.387506,5.651471
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,103.783651,-211.925149,-227.121250,4.224708
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,69.639017,-140.944586,876.374496,5.786348
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,-24.013824,192.102405,-391.081276,8.143262
4,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,2.441547,172.464881,-405.493732,18.545150
5,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,90.931713,149.027266,-426.544715,18.208570
6,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,89.540769,196.405159,-515.073322,16.381276
7,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,81.509646,54.957219,-150.346423,10.362321
8,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,105.055792,19.825260,-91.247251,21.089619
9,1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...,-124.834262,127.247155,-473.064479,10.465854
10,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,-106.901301,21.922987,-126.916900,9.745259
11,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,2.263816,33.526418,-170.636950,7.168542

### pandas function

In [54]:
csv_1 =pd.read_csv("/home/yksaini/GENAI/GENAI/4-Pandas/data.csv")

csv_1

,seriesuid,coordX,coordY,coordZ,diameter_mm
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-128.699421,-175.319272,-298.387506,5.651471
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,103.783651,-211.925149,-227.121250,4.224708
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,69.639017,-140.944586,876.374496,5.786348
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,-24.013824,192.102405,-391.081276,8.143262
4,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,2.441547,172.464881,-405.493732,18.545150
5,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,90.931713,149.027266,-426.544715,18.208570
6,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,89.540769,196.405159,-515.073322,16.381276
7,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,81.509646,54.957219,-150.346423,10.362321
8,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,105.055792,19.825260,-91.247251,21.089619
9,1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...,-124.834262,127.247155,-473.064479,10.465854
10,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,-106.901301,21.922987,-126.916900,9.745259
11,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,2.263816,33.526418,-170.636950,7.168542

In [55]:
csv_1.index

RangeIndex(start=0, stop=12, step=1)

In [56]:
csv_1.columns

Index(['seriesuid', 'coordX', 'coordY', 'coordZ', 'diameter_mm'], dtype='str')

In [57]:
csv_1.describe

<bound method NDFrame.describe of                                             seriesuid      coordX      coordY  \
0   1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222... -128.699421 -175.319272
1   1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...  103.783651 -211.925149
2   1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...   69.639017 -140.944586
3   1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...  -24.013824  192.102405
4   1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...    2.441547  172.464881
5   1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...   90.931713  149.027266
6   1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...   89.540769  196.405159
7   1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...   81.509646   54.957219
8   1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...  105.055792   19.825260
9   1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760... -124.834262  127.247155
10  1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985... -106.901301   21.922987
11  1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...    2.263816   33.526418

        coordZ  diameter_mm
0  -298.387506     5.651471
1  -227.121250     4.224708
2   876.374496     5.786348
3  -391.081276     8.143262
4  -405.493732    18.545150
5  -426.544715    18.208570
6  -515.073322    16.381276
7  -150.346423    10.362321
8   -91.247251    21.089619
9  -473.064479    10.465854
10 -126.916900     9.745259
11 -170.636950     7.168542  >

In [58]:
csv_1.head(5)

,seriesuid,coordX,coordY,coordZ,diameter_mm
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-128.699421,-175.319272,-298.387506,5.651471
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,103.783651,-211.925149,-227.121250,4.224708
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,69.639017,-140.944586,876.374496,5.786348
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,-24.013824,192.102405,-391.081276,8.143262
4,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,2.441547,172.464881,-405.493732,18.545150

In [59]:
csv_1.tail(5)

,seriesuid,coordX,coordY,coordZ,diameter_mm
7,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,81.509646,54.957219,-150.346423,10.362321
8,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,105.055792,19.825260,-91.247251,21.089619
9,1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...,-124.834262,127.247155,-473.064479,10.465854
10,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,-106.901301,21.922987,-126.916900,9.745259
11,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,2.263816,33.526418,-170.636950,7.168542

In [60]:
csv_1[:2]

,seriesuid,coordX,coordY,coordZ,diameter_mm
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-128.699421,-175.319272,-298.387506,5.651471
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,103.783651,-211.925149,-227.121250,4.224708

In [61]:
csv_1[6:12]

,seriesuid,coordX,coordY,coordZ,diameter_mm
6,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,89.540769,196.405159,-515.073322,16.381276
7,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,81.509646,54.957219,-150.346423,10.362321
8,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,105.055792,19.825260,-91.247251,21.089619
9,1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...,-124.834262,127.247155,-473.064479,10.465854
10,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,-106.901301,21.922987,-126.916900,9.745259
11,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,2.263816,33.526418,-170.636950,7.168542

In [62]:
print(type(csv_1))

<class 'pandas.DataFrame'>

In [63]:
csv_1.index.array

<NumpyExtensionArray>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
Length: 12, dtype: int64

In [64]:
csv_1.to_numpy()

array([['1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860',
        -128.6994211, -175.3192718, -298.3875064, 5.651470635],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860',
        103.7836509, -211.9251487, -227.12125, 4.224708481],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793540579077826395208',
        69.63901724, -140.9445859, 876.3744957, 5.786347814],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016233746780170740405',
        -24.0138242, 192.1024053, -391.0812764, 8.143261683],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016233746780170740405',
        2.441546798, 172.4648812, -405.4937318, 18.54514997],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016233746780170740405',
        90.93171321, 149.0272657, -426.5447146, 18.20857028],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016233746780170740405',
        89.54076865, 196.4051593, -515.0733216, 16.38127631],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028192176989979435275',
        81.50964574, 54.9572186, -150.3464233, 10.36232088],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408431413578140925249',
        105.0557924, 19.82526014, -91.24725078, 21.08961863],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760173137525888934217',
        -124.8342624, 127.2471546, -473.0644785, 10.46585391],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985881418176186711228',
        -106.9013014, 21.92298672, -126.9169003, 9.745258507],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370116976238911317774',
        2.263815885, 33.52641757, -170.6369497, 7.16854239]], dtype=object)

In [65]:
import numpy as np
v =np.asarray(csv_1)
v

array([['1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860',
        -128.6994211, -175.3192718, -298.3875064, 5.651470635],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860',
        103.7836509, -211.9251487, -227.12125, 4.224708481],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793540579077826395208',
        69.63901724, -140.9445859, 876.3744957, 5.786347814],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016233746780170740405',
        -24.0138242, 192.1024053, -391.0812764, 8.143261683],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016233746780170740405',
        2.441546798, 172.4648812, -405.4937318, 18.54514997],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016233746780170740405',
        90.93171321, 149.0272657, -426.5447146, 18.20857028],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016233746780170740405',
        89.54076865, 196.4051593, -515.0733216, 16.38127631],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028192176989979435275',
        81.50964574, 54.9572186, -150.3464233, 10.36232088],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408431413578140925249',
        105.0557924, 19.82526014, -91.24725078, 21.08961863],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760173137525888934217',
        -124.8342624, 127.2471546, -473.0644785, 10.46585391],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985881418176186711228',
        -106.9013014, 21.92298672, -126.9169003, 9.745258507],
       ['1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370116976238911317774',
        2.263815885, 33.52641757, -170.6369497, 7.16854239]], dtype=object)

In [66]:
csv_1

,seriesuid,coordX,coordY,coordZ,diameter_mm
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-128.699421,-175.319272,-298.387506,5.651471
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,103.783651,-211.925149,-227.121250,4.224708
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,69.639017,-140.944586,876.374496,5.786348
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,-24.013824,192.102405,-391.081276,8.143262
4,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,2.441547,172.464881,-405.493732,18.545150
5,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,90.931713,149.027266,-426.544715,18.208570
6,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,89.540769,196.405159,-515.073322,16.381276
7,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,81.509646,54.957219,-150.346423,10.362321
8,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,105.055792,19.825260,-91.247251,21.089619
9,1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...,-124.834262,127.247155,-473.064479,10.465854
10,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,-106.901301,21.922987,-126.916900,9.745259
11,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,2.263816,33.526418,-170.636950,7.168542

In [69]:
csv_1.loc[2,"coordX"] = 25

csv_1

,seriesuid,coordX,coordY,coordZ,diameter_mm
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-128.699421,-175.319272,-298.387506,5.651471
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,103.783651,-211.925149,-227.121250,4.224708
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,25.000000,-140.944586,876.374496,5.786348
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,-24.013824,192.102405,-391.081276,8.143262
4,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,2.441547,172.464881,-405.493732,18.545150
5,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,90.931713,149.027266,-426.544715,18.208570
6,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,89.540769,196.405159,-515.073322,16.381276
7,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,81.509646,54.957219,-150.346423,10.362321
8,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,105.055792,19.825260,-91.247251,21.089619
9,1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...,-124.834262,127.247155,-473.064479,10.465854
10,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,-106.901301,21.922987,-126.916900,9.745259
11,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,2.263816,33.526418,-170.636950,7.168542

In [71]:
csv_1.loc[[2,3],["coordX","coordY"]]

      coordX      coordY
2  25.000000 -140.944586
3 -24.013824  192.102405

In [73]:
csv_1.loc[:,["coordX","coordY"]]

        coordX      coordY
0  -128.699421 -175.319272
1   103.783651 -211.925149
2    25.000000 -140.944586
3   -24.013824  192.102405
4     2.441547  172.464881
5    90.931713  149.027266
6    89.540769  196.405159
7    81.509646   54.957219
8   105.055792   19.825260
9  -124.834262  127.247155
10 -106.901301   21.922987
11    2.263816   33.526418

In [74]:
csv_1.loc[[2,3],:]

,seriesuid,coordX,coordY,coordZ,diameter_mm
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,25.000000,-140.944586,876.374496,5.786348
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,-24.013824,192.102405,-391.081276,8.143262

In [75]:
csv_1.iloc[0,1]

np.float64(-128.6994211)

In [77]:
csv_1.drop("coordX",axis=1)

,seriesuid,coordY,coordZ,diameter_mm
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-175.319272,-298.387506,5.651471
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-211.925149,-227.121250,4.224708
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,-140.944586,876.374496,5.786348
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,192.102405,-391.081276,8.143262
4,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,172.464881,-405.493732,18.545150
5,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,149.027266,-426.544715,18.208570
6,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,196.405159,-515.073322,16.381276
7,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,54.957219,-150.346423,10.362321
8,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,19.825260,-91.247251,21.089619
9,1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...,127.247155,-473.064479,10.465854
10,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,21.922987,-126.916900,9.745259
11,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,33.526418,-170.636950,7.168542