### dropna &fillna

In [35]:
import pandas as pd

In [36]:
csv2=pd.read_csv("/home/yksaini/GENAI/GENAI/4-Pandas/data.csv")

csv2

,seriesuid,coordX,coordY,coordZ,diameter_mm
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-128.699421,-175.319272,-298.387506,5.651471
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,103.783651,-211.925149,-227.121250,4.224708
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,69.639017,-140.944586,876.374496,5.786348
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,-24.013824,192.102405,-391.081276,8.143262
4,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,2.441547,172.464881,-405.493732,18.545150
5,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,90.931713,149.027266,-426.544715,NaN
6,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,NaN,196.405159,-515.073322,16.381276
7,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,81.509646,54.957219,-150.346423,10.362321
8,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,105.055792,19.825260,-91.247251,21.089619
9,1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...,NaN,127.247155,-473.064479,10.465854
10,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,-106.901301,21.922987,-126.916900,9.745259
11,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,2.263816,33.526418,-170.636950,7.168542

In [37]:
# droped nan value
csv2.dropna()

,seriesuid,coordX,coordY,coordZ,diameter_mm
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-128.699421,-175.319272,-298.387506,5.651471
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,103.783651,-211.925149,-227.121250,4.224708
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,69.639017,-140.944586,876.374496,5.786348
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,-24.013824,192.102405,-391.081276,8.143262
4,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,2.441547,172.464881,-405.493732,18.545150
7,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,81.509646,54.957219,-150.346423,10.362321
8,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,105.055792,19.825260,-91.247251,21.089619
10,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,-106.901301,21.922987,-126.916900,9.745259
11,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,2.263816,33.526418,-170.636950,7.168542

In [38]:
#collem wise
csv2.dropna(axis=1)

                                            seriesuid      coordY      coordZ
0   1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222... -175.319272 -298.387506
1   1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222... -211.925149 -227.121250
2   1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793... -140.944586  876.374496
3   1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...  192.102405 -391.081276
4   1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...  172.464881 -405.493732
5   1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...  149.027266 -426.544715
6   1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...  196.405159 -515.073322
7   1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...   54.957219 -150.346423
8   1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...   19.825260  -91.247251
9   1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...  127.247155 -473.064479
10  1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...   21.922987 -126.916900
11  1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...   33.526418 -170.636950

In [39]:
csv2.dropna(subset=["coordY"])

,seriesuid,coordX,coordY,coordZ,diameter_mm
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-128.699421,-175.319272,-298.387506,5.651471
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,103.783651,-211.925149,-227.121250,4.224708
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,69.639017,-140.944586,876.374496,5.786348
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,-24.013824,192.102405,-391.081276,8.143262
4,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,2.441547,172.464881,-405.493732,18.545150
5,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,90.931713,149.027266,-426.544715,NaN
6,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,NaN,196.405159,-515.073322,16.381276
7,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,81.509646,54.957219,-150.346423,10.362321
8,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,105.055792,19.825260,-91.247251,21.089619
9,1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...,NaN,127.247155,-473.064479,10.465854
10,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,-106.901301,21.922987,-126.916900,9.745259
11,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,2.263816,33.526418,-170.636950,7.168542

In [40]:
csv2.fillna("saini")

,seriesuid,coordX,coordY,coordZ,diameter_mm
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-128.699421,-175.319272,-298.387506,5.651471
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,103.783651,-211.925149,-227.121250,4.224708
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,69.639017,-140.944586,876.374496,5.786348
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,-24.013824,192.102405,-391.081276,8.143262
4,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,2.441547,172.464881,-405.493732,18.54515
5,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,90.931713,149.027266,-426.544715,saini
6,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,saini,196.405159,-515.073322,16.381276
7,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,81.509646,54.957219,-150.346423,10.362321
8,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,105.055792,19.825260,-91.247251,21.089619
9,1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...,saini,127.247155,-473.064479,10.465854
10,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,-106.901301,21.922987,-126.916900,9.745259
11,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,2.263816,33.526418,-170.636950,7.168542

In [41]:
csv2.fillna({"coordX":"yogesh"})

,seriesuid,coordX,coordY,coordZ,diameter_mm
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-128.699421,-175.319272,-298.387506,5.651471
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,103.783651,-211.925149,-227.121250,4.224708
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,69.639017,-140.944586,876.374496,5.786348
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,-24.013824,192.102405,-391.081276,8.143262
4,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,2.441547,172.464881,-405.493732,18.545150
5,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,90.931713,149.027266,-426.544715,NaN
6,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,yogesh,196.405159,-515.073322,16.381276
7,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,81.509646,54.957219,-150.346423,10.362321
8,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,105.055792,19.825260,-91.247251,21.089619
9,1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...,yogesh,127.247155,-473.064479,10.465854
10,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,-106.901301,21.922987,-126.916900,9.745259
11,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,2.263816,33.526418,-170.636950,7.168542

In [42]:
csv2 = csv2.ffill()

In [43]:
csv2

,seriesuid,coordX,coordY,coordZ,diameter_mm
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-128.699421,-175.319272,-298.387506,5.651471
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,103.783651,-211.925149,-227.121250,4.224708
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,69.639017,-140.944586,876.374496,5.786348
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,-24.013824,192.102405,-391.081276,8.143262
4,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,2.441547,172.464881,-405.493732,18.545150
5,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,90.931713,149.027266,-426.544715,18.545150
6,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,90.931713,196.405159,-515.073322,16.381276
7,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,81.509646,54.957219,-150.346423,10.362321
8,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,105.055792,19.825260,-91.247251,21.089619
9,1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...,105.055792,127.247155,-473.064479,10.465854
10,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,-106.901301,21.922987,-126.916900,9.745259
11,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,2.263816,33.526418,-170.636950,7.168542

In [44]:
csv2 = csv2.bfill()

In [45]:
csv2

,seriesuid,coordX,coordY,coordZ,diameter_mm
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-128.699421,-175.319272,-298.387506,5.651471
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,103.783651,-211.925149,-227.121250,4.224708
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,69.639017,-140.944586,876.374496,5.786348
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,-24.013824,192.102405,-391.081276,8.143262
4,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,2.441547,172.464881,-405.493732,18.545150
5,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,90.931713,149.027266,-426.544715,18.545150
6,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,90.931713,196.405159,-515.073322,16.381276
7,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,81.509646,54.957219,-150.346423,10.362321
8,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,105.055792,19.825260,-91.247251,21.089619
9,1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...,105.055792,127.247155,-473.064479,10.465854
10,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,-106.901301,21.922987,-126.916900,9.745259
11,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,2.263816,33.526418,-170.636950,7.168542

In [46]:
csv2.fillna("saini",limit= 1)

,seriesuid,coordX,coordY,coordZ,diameter_mm
0,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,-128.699421,-175.319272,-298.387506,5.651471
1,1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222...,103.783651,-211.925149,-227.121250,4.224708
2,1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793...,69.639017,-140.944586,876.374496,5.786348
3,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,-24.013824,192.102405,-391.081276,8.143262
4,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,2.441547,172.464881,-405.493732,18.545150
5,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,90.931713,149.027266,-426.544715,18.545150
6,1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016...,90.931713,196.405159,-515.073322,16.381276
7,1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028...,81.509646,54.957219,-150.346423,10.362321
8,1.3.6.1.4.1.14519.5.2.1.6279.6001.102681962408...,105.055792,19.825260,-91.247251,21.089619
9,1.3.6.1.4.1.14519.5.2.1.6279.6001.104562737760...,105.055792,127.247155,-473.064479,10.465854
10,1.3.6.1.4.1.14519.5.2.1.6279.6001.105495028985...,-106.901301,21.922987,-126.916900,9.745259
11,1.3.6.1.4.1.14519.5.2.1.6279.6001.106164978370...,2.263816,33.526418,-170.636950,7.168542