### merge

In [1]:
import pandas as pd

In [11]:
var1 =pd.DataFrame({"A":[1,2,3,4,5],"B":[11,12,13,14,15]})
var2 =pd.DataFrame({"A":[1,2,3,4,5],"B":[11,12,43,64,45]})

pd.merge(var1,var2,how ="outer")

   A   B
0  1  11
1  2  12
2  3  13
3  3  43
4  4  14
5  4  64
6  5  15
7  5  45

In [12]:
## Concat

sr1 =pd.Series([1,2,3,4])
sr2 =pd.Series([11,22,33,45])

pd.concat([sr1,sr2])

0     1
1     2
2     3
3     4
0    11
1    22
2    33
3    45
dtype: int64

In [13]:
pd.concat([var1,var2])

   A   B
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15
0  1  11
1  2  12
2  3  43
3  4  64
4  5  45